### ISSUE TITLE
kafka 模式，控制台报canal 消费异常

### ISSUE THREAD

**Issue by GITleonine1989** [xizixuejie/canal-spring#16]
使用kafka 模式控制台报错canal 消费异常 回滚消息
2023-11-07 18:06:27.474 ERROR 33704 --- [l-client-thread] i.x.canal.core.client.KafkaCanalClient   : canal 消费异常 回滚消息

com.alibaba.fastjson2.JSONException: error, offset 1, char 
	at com.alibaba.fastjson2.JSONReaderUTF16.skipValue(JSONReaderUTF16.java:1585) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:49) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:167) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getFlatListWithoutAck(KafkaCanalConnector.java:233) ~[canal.client-1.1.6.jar:na]
	at io.xzxj.canal.core.client.KafkaCanalClient.handleListening(KafkaCanalClient.java:31) ~[canal-client-core-0.0.7.jar:na]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_382]

打断点跟踪了一下，是在 getFlatListWithoutAck 这个方法里的  JSON.parseObject  报错，
我看 传给JSON.parseObject 好像是乱码

![image](https://github.com/xizixuejie/canal-spring/assets/7582490/0ef7b95b-352f-466f-aa2f-ee870a6988b0)

**Comment by GITleonine1989** [comment]
乱码是因为  canal 的配置项 canal.mq.flatMessagep=false 导致的，改成true之后没有乱码 还是解析报错。。。

**Comment by xizixuejie** [comment]
可以贴一下kafka里的消息json，我试下嘛

**Comment by GITleonine1989** [comment]
@xizixuejie 是canal ,那边的问题，升级到1.1.7 就好了，但是1.1.7他们引入的JSON包错了，导致了新的问题 https://github.com/alibaba/canal/pull/4927，我本地先把KafkaCanalConnector这个类的重写了一下（改成import fastjson2 ），解决了
