### ISSUE TITLE
实体类字段属性转换异常

### ISSUE THREAD

**Issue by xizixuejie** [xizixuejie/canal-spring#20]
如果实体类中的属性没有在 `io.xzxj.canal.core.util.StringConvertUtil#convertType` 方法中定义，会抛出异常

实体类属性
``` java
@Data
@TableName("t_test")
public class TestEntity {

    private Long id;

    private String name;

    @TableField("f_age")
    private Integer age;

    @TableField("f_gender")
    private Integer gender;

    private byte[] annex;

}
```

异常信息
```
java.lang.RuntimeException: parse event has an error , data:[{f_gender=3, name=3, id=47, f_age=3, annex=ab}]
	at io.xzxj.canal.core.handler.AbstractFlatMessageHandler.handleMessage(AbstractFlatMessageHandler.java:60) ~[classes/:na]
	at io.xzxj.canal.core.handler.impl.AsyncFlatMessageHandlerImpl.lambda$handleMessage$0(AsyncFlatMessageHandlerImpl.java:30) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_341]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_341]
Caused by: java.lang.IllegalArgumentException: Can not set [B field io.xzxj.canal.example.entity.TestEntity.annex to null value
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_341]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_341]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0_341]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_341]
	at io.xzxj.canal.core.util.TableFieldUtil.setFieldValue(TableFieldUtil.java:98) ~[classes/:na]
	at io.xzxj.canal.core.factory.MapConvertFactory.newInstance(MapConvertFactory.java:26) ~[classes/:na]
	at io.xzxj.canal.core.factory.MapConvertFactory.newInstance(MapConvertFactory.java:13) ~[classes/:na]
	at io.xzxj.canal.core.factory.AbstractConvertFactory.newInstance(AbstractConvertFactory.java:22) ~[classes/:na]
	at io.xzxj.canal.core.handler.impl.MapRowDataHandlerImpl.handleRowData(MapRowDataHandlerImpl.java:40) ~[classes/:na]
	at io.xzxj.canal.core.handler.impl.MapRowDataHandlerImpl.handleRowData(MapRowDataHandlerImpl.java:17) ~[classes/:na]
	at io.xzxj.canal.core.handler.AbstractFlatMessageHandler.handleMessage(AbstractFlatMessageHandler.java:58) ~[classes/:na]
	... 4 common frames omitted
```

**Comment by xizixuejie** [comment]
应该改成可以用户自己加转换类的功能，而不是在 `StringConvertUtil` 的 if else 里写死
