### ISSUE TITLE
从Canal拿到数据之后进行实体类转换时如果value为null反射会报错

### ISSUE THREAD

**Issue by QinJiapeng** [xizixuejie/canal-spring#22]
问题现象：
从Canal拿到数据之后进行实体类转换时如果value为null反射会报错
java.lang.IllegalArgumentException: Can not set java.time.LocalDateTime field com.xxx.mybatis.base.BaseEntity.updateTime to null value
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_381]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_381]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0_381]

问题原因：
源码位置：`io.xzxj.canal.core.util.TableFieldUtil#setFieldValue`
![image](https://github.com/xizixuejie/canal-spring/assets/84890012/35578fe4-42d4-429a-a6d2-9d3d6f1b46b6)
value的值实际是空字符串""
应增加判断
if(value=="") value = null;

**Comment by xizixuejie** [comment]
谢谢，v0.0.12版本修改了
